config/routes.rb
Rails.application.routes.draw do
  resources :ramals do
    collection do
      get 'remove_all'
    end
  end
  post 'import_from_excel' => "ramals#import_from_excel"
  get 'home/index'
  get 'home/news_setembro'
  root "home#news_setembro"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ramal.rb
class Ramal < ApplicationRecord

    require 'csv'

    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            Ramal.create! row.to_hash
            t.string :setor
            t.string :telefone
            t.string :email
            t.string :department
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ramals_controller.rb
class RamalsController < ApplicationController
  before_action :set_ramal, only: %i[ show edit update destroy ]

  # GET /ramals or /ramals.json
  def index
    @ramals = Ramal.all
  end

  def remove_all
    Ramal.delete_all
    flash[:notice] = "Lista removida com sucesso"
    redirect_to ramals_path
  end

  def import_from_excel
    file = params[:file]
    begin
      file_ext = File.extname(file.original_filename)
      raise "Unknown file type: #{file.original_filename}" unless [".xls", ".xlsx"].include?(file_ext)
      spreadsheet = (file_ext == ".xls") ? Roo::Excel.new(file.path) : Roo::Excelx.new(file.path)
      header = spreadsheet.row(1)
      ## We are iterating from row 2 because we have left row one for header
      (2..spreadsheet.last_row).each do |i|
        Ramal.create(setor: spreadsheet.row(i)[0], telefone: spreadsheet.row(i)[1], email: spreadsheet.row(i)[2], department: spreadsheet.row(i)[3])
      end
      flash[:notice] = "Lista importada"
      redirect_to ramals_path 
    rescue Exception => e
      flash[:notice] = "Problemas com o arquivo"
      redirect_to ramals_path 
    end
 end

  # GET /ramals/1 or /ramals/1.json
  def show
  end

  # GET /ramals/new
  def new
    @ramal = Ramal.new
  end

  # GET /ramals/1/edit
  def edit
  end

  # POST /ramals or /ramals.json
  def create
    @ramal = Ramal.new(ramal_params)

    respond_to do |format|
      if @ramal.save
        format.html { redirect_to ramal_url(@ramal), notice: "Ramal adicionado com sucesso." }
        format.json { render :show, status: :created, location: @ramal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ramal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ramals/1 or /ramals/1.json
  def update
    respond_to do |format|
      if @ramal.update(ramal_params)
        format.html { redirect_to ramal_url(@ramal), notice: "Ramal atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @ramal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ramal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ramals/1 or /ramals/1.json
  def destroy
    @ramal.destroy

    respond_to do |format|
      format.html { redirect_to ramals_url, notice: "Ramal removido com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ramal
      @ramal = Ramal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ramal_params
      params.require(:ramal).permit(:setor, :telefone, :email, :department)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ramals_helper.rb
module RamalsHelper
end

app/views/home/index.html.erb
<main>
<div class="container">
        <div class="row mb-2 mt-5">
                <div class="col-md-6">
                        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                                <div class="col p-4 d-flex flex-column position-static">
                                        <strong class="d-inline-block mb-2 text-primary">World</strong>
                                        <h3 class="mb-0">Featured post</h3>
                                        <div class="mb-1 text-muted">Nov 12</div>
                                        <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                                        <a href="#" class="stretched-link">Continue reading</a>
                                </div>
                                <div class="col-auto d-none d-lg-block">
                                        <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

                                </div>
                        </div>
                </div>
                <div class="col-md-6">
                        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                                <div class="col p-4 d-flex flex-column position-static">
                                        <strong class="d-inline-block mb-2 text-success">Design</strong>
                                        <h3 class="mb-0">Post title</h3>
                                        <div class="mb-1 text-muted">Nov 11</div>
                                        <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                                        <a href="#" class="stretched-link">Continue reading</a>
                                </div>
                                <div class="col-auto d-none d-lg-block">
                                        <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

                                </div>
                        </div>
                </div>
        </div>

<div class="row g-5 mb-5">
  <div class="col-md-8">
    <h3 class="pb-4 mb-4 fst-italic border-bottom">
      From the Firehose
    </h3>

    <article class="blog-post">
      <h2 class="blog-post-title mb-1">Sample blog post</h2>
      <p class="blog-post-meta">January 1, 2021 by <a href="#">Mark</a></p>

      <p>This blog post shows a few different types of content that’s supported and styled with Bootstrap. Basic typography, lists, tables, images, code, and more are all supported as expected.</p>
      <hr>
      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
      <h2>Blockquotes</h2>
      <p>This is an example blockquote in action:</p>
      <blockquote class="blockquote">
        <p>Quoted text goes here.</p>
      </blockquote>
      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
      <h3>Example lists</h3>
      <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout. This is an example unordered list:</p>
      <ul>
        <li>First list item</li>
        <li>Second list item with a longer description</li>
        <li>Third list item to close it out</li>
      </ul>
      <p>And this is an ordered list:</p>
      <ol>
        <li>First list item</li>
        <li>Second list item with a longer description</li>
        <li>Third list item to close it out</li>
      </ol>
      <p>And this is a definition list:</p>
      <dl>
        <dt>HyperText Markup Language (HTML)</dt>
        <dd>The language used to describe and define the content of a Web page</dd>
        <dt>Cascading Style Sheets (CSS)</dt>
        <dd>Used to describe the appearance of Web content</dd>
        <dt>JavaScript (JS)</dt>
        <dd>The programming language used to build advanced Web sites and applications</dd>
      </dl>
      <h2>Inline HTML elements</h2>
      <p>HTML defines a long list of available inline tags, a complete list of which can be found on the <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element">Mozilla Developer Network</a>.</p>
      <ul>
        <li><strong>To bold text</strong>, use <code class="language-plaintext highlighter-rouge">&lt;strong&gt;</code>.</li>
        <li><em>To italicize text</em>, use <code class="language-plaintext highlighter-rouge">&lt;em&gt;</code>.</li>
        <li>Abbreviations, like <abbr title="HyperText Markup Language">HTML</abbr> should use <code class="language-plaintext highlighter-rouge">&lt;abbr&gt;</code>, with an optional <code class="language-plaintext highlighter-rouge">title</code> attribute for the full phrase.</li>
        <li>Citations, like <cite>— Mark Otto</cite>, should use <code class="language-plaintext highlighter-rouge">&lt;cite&gt;</code>.</li>
        <li><del>Deleted</del> text should use <code class="language-plaintext highlighter-rouge">&lt;del&gt;</code> and <ins>inserted</ins> text should use <code class="language-plaintext highlighter-rouge">&lt;ins&gt;</code>.</li>
        <li>Superscript <sup>text</sup> uses <code class="language-plaintext highlighter-rouge">&lt;sup&gt;</code> and subscript <sub>text</sub> uses <code class="language-plaintext highlighter-rouge">&lt;sub&gt;</code>.</li>
      </ul>
      <p>Most of these elements are styled by browsers with few modifications on our part.</p>
      <h2>Heading</h2>
      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
      <h3>Sub-heading</h3>
      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
      <pre><code>Example code block</code></pre>
      <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout.</p>
    </article>

    <article class="blog-post">
      <h2 class="blog-post-title mb-1">Another blog post</h2>
      <p class="blog-post-meta">December 23, 2020 by <a href="#">Jacob</a></p>

      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
      <blockquote>
        <p>Longer quote goes here, maybe with some <strong>emphasized text</strong> in the middle of it.</p>
      </blockquote>
      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
      <h3>Example table</h3>
      <p>And don't forget about tables in these posts:</p>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Upvotes</th>
            <th>Downvotes</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Alice</td>
            <td>10</td>
            <td>11</td>
          </tr>
          <tr>
            <td>Bob</td>
            <td>4</td>
            <td>3</td>
          </tr>
          <tr>
            <td>Charlie</td>
            <td>7</td>
            <td>9</td>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <td>Totals</td>
            <td>21</td>
            <td>23</td>
          </tr>
        </tfoot>
      </table>

      <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout.</p>
    </article>

    <article class="blog-post">
      <h2 class="blog-post-title mb-1">New feature</h2>
      <p class="blog-post-meta">December 14, 2020 by <a href="#">Chris</a></p>

      <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
      <ul>
        <li>First list item</li>
        <li>Second list item with a longer description</li>
        <li>Third list item to close it out</li>
      </ul>
      <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout.</p>
    </article>

    <nav class="blog-pagination" aria-label="Pagination">
      <a class="btn btn-outline-primary rounded-pill" href="#">Older</a>
      <a class="btn btn-outline-secondary rounded-pill disabled">Newer</a>
    </nav>

  </div>

  <div class="col-md-4">
    <div class="position-sticky" style="top: 2rem;">
      <div class="p-4 mb-3 bg-light rounded">
        <h4 class="fst-italic">About</h4>
        <p class="mb-0">Customize this section to tell your visitors a little bit about your publication, writers, content, or something else entirely. Totally up to you.</p>
      </div>

      <div class="p-4">
        <h4 class="fst-italic">Archives</h4>
        <ol class="list-unstyled mb-0">
          <li><a href="#">March 2021</a></li>
          <li><a href="#">February 2021</a></li>
          <li><a href="#">January 2021</a></li>
          <li><a href="#">December 2020</a></li>
          <li><a href="#">November 2020</a></li>
          <li><a href="#">October 2020</a></li>
          <li><a href="#">September 2020</a></li>
          <li><a href="#">August 2020</a></li>
          <li><a href="#">July 2020</a></li>
          <li><a href="#">June 2020</a></li>
          <li><a href="#">May 2020</a></li>
          <li><a href="#">April 2020</a></li>
        </ol>
      </div>

      <div class="p-4">
        <h4 class="fst-italic">Elsewhere</h4>
        <ol class="list-unstyled">
          <li><a href="#">GitHub</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </div>
  </div>
</div>
</div>
        
</main>

app/views/home/news_setembro.html.erb
<div class="container">
      <ul
        class="
          nav nav-tabs
          d-flex
          justify-content-between
          align-items-center
          text-dark
          p-3
        "
      >
        <li class="nav-item">
          <a
            href="#"
            class="p-1 border rounded-circle"
            id="prev_page"
            title="previous page"
            data-bs-toggle="tooltip"
            data-bs-placement="bottom"
          >
            <i class="bi bi-chevron-left"></i
          ></a>

          <input
            type="number"
            id="current_page"
            value="1"
            class="d-inline form-control"
          />

          <a
            href="#"
            class="p-1 border rounded-circle"
            id="next_page"
            data-bs-toggle="tooltip"
            data-bs-placement="bottom"
            title="next page"
            ><i class="bi bi-chevron-right"></i
          ></a>

          <!-- page 1 of 5 -->
          Page
          <span id="page_num"></span>
          of
          <span id="page_count"></span>
        </li>

        <li class="nav-item">
          <button
            class="rounded-circle p-2 border-0 btn btn-primary"
            id="zoom_in"
            data-bs-toggle="tooltip"
            data-bs-placement="bottom"
            title="zoom in"
          >
            <i class="bi bi-zoom-in"></i>
          </button>

          <button
            class="rounded-circle p-2 border-0 btn btn-primary"
            id="zoom_out"
            data-bs-toggle="tooltip"
            data-bs-placement="bottom"
            title="zoom out"
          >
            <i class="bi bi-zoom-out"></i>
          </button>
        </li>
      </ul>

      <!-- canvas to place the PDF -->
      <canvas
        id="canvas"
        class="
          d-flex
          flex-column
          justify-content-center
          align-items-center
          mx-auto
        "
      >
      </canvas>
    </div>

    <!-- PDF.js CDN -->
    <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.10.377/build/pdf.min.js"></script>
    <script>
        const pdf = 'assets/documents/document.pdf';

        const pageNum = document.querySelector('#page_num');
        const pageCount = document.querySelector('#page_count');
        const currentPage = document.querySelector('#current_page');
        const previousPage = document.querySelector('#prev_page');
        const nextPage = document.querySelector('#next_page');
        const zoomIn = document.querySelector('#zoom_in');
        const zoomOut = document.querySelector('#zoom_out');

        const initialState = {
        pdfDoc: null,
        currentPage: 1,
        pageCount: 0,
        zoom: 1,
        };

        // Render the page
        const renderPage = () => {
        // load the first page
        initialState.pdfDoc.getPage(initialState.currentPage).then((page) => {
            console.log('page', page);

            const canvas = document.querySelector('#canvas');
            const ctx = canvas.getContext('2d');
            const viewport = page.getViewport({ scale: initialState.zoom });

            canvas.height = viewport.height;
            canvas.width = viewport.width;

            // Render PDF page into canvas context
            const renderCtx = {
            canvasContext: ctx,
            viewport: viewport,
            };

            page.render(renderCtx);

            pageNum.textContent = initialState.currentPage;
        });
        };

        // Load the Document
        pdfjsLib
        .getDocument(pdf)
        .promise.then((data) => {
            initialState.pdfDoc = data;
            console.log('pdfDocument', initialState.pdfDoc);

            pageCount.textContent = initialState.pdfDoc.numPages;

            renderPage();
        })
        .catch((err) => {
            alert(err.message);
        });

        const showPrevPage = () => {
        if (initialState.pdfDoc === null || initialState.currentPage <= 1) return;
        initialState.currentPage--;
        // render the current page
        currentPage.value = initialState.currentPage;
        renderPage();
        };

        const showNextPage = () => {
        if (
            initialState.pdfDoc === null ||
            initialState.currentPage >= initialState.pdfDoc._pdfInfo.numPages
        )
            return;

        initialState.currentPage++;
        currentPage.value = initialState.currentPage;
        renderPage();
        };

        // Button Events
        previousPage.addEventListener('click', showPrevPage);
        nextPage.addEventListener('click', showNextPage);

        // Keypress Event
        currentPage.addEventListener('keypress', (event) => {
        if (initialState.pdfDoc === null) return;
        // get the key code
        const keycode = event.keyCode ? event.keyCode : event.which;

        if (keycode === 13) {
            // get the new page number and render it
            let desiredPage = currentPage.valueAsNumber;
            initialState.currentPage = Math.min(
            Math.max(desiredPage, 1),
            initialState.pdfDoc._pdfInfo.numPages
            );

            currentPage.value = initialState.currentPage;
            renderPage();
        }
        });

        // Zoom Events
        zoomIn.addEventListener('click', () => {
        if (initialState.pdfDoc === null) return;
        initialState.zoom *= 4 / 3;
        renderPage();
        });

        zoomOut.addEventListener('click', () => {
        if (initialState.pdfDoc === null) return;
        initialState.zoom *= 2 / 3;
        renderPage();
        });

        // Tooltip

        const tooltipTriggerList = [].slice.call(
        document.querySelectorAll('[data-bs-toggle="tooltip"]')
        );
        const tooltipList = tooltipTriggerList.map((tooltipTriggerEl) => {
        return new bootstrap.Tooltip(tooltipTriggerEl);
        });

    </script>

app/views/layouts/_caroussel.html.erb
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Example headline.</h1>
            <p>Some representative placeholder content for the first slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>Intranet - Hegv</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <%= render :partial => '/layouts/header' %>
    <%= yield %>
    <%= render :partial => '/layouts/footer' %>
  </body>
</html>

app/views/ramals/_ramal.html.erb
<div id="<%= dom_id ramal %>">
  <p>
    <strong>Setor:</strong>
    <%= ramal.setor %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= ramal.telefone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= ramal.email %>
  </p>

  <p>
    <strong>Departamento:</strong>
    <%= ramal.department %>
  </p>

</div>

app/views/ramals/edit.html.erb
<h1>Editing ramal</h1>

<%= render "form", ramal: @ramal %>

<br>

<div>
  <%= link_to "Show this ramal", @ramal %> |
  <%= link_to "Back to ramals", ramals_path %>
</div>

app/views/ramals/index.html.erb
<div class="container">

<div class="row align-items-center mt-5">
    <div class="col-3">
    
    </div>
    <div class="col-6">
      <h1>Ramais</h1>
    </div>
    <div class="col-3">
    
    </div>
  </div>

  <div class="row align-items-center">
    <div class="col-6">
    <!--<h3>Importar lista de ramais</h3>
      <%= form_tag import_from_excel_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Importar", :class=> "btn btn-success"%>
      <% end %>-->
    </div>
    <div class="col-6">
      <!--<h3>Limpar lista de ramais</h3>
      <%= link_to "Limpar lista", remove_all_ramals_path, :method => :get, class: "btn btn-danger" %>-->
    </div>
  </div>
  <div class="row align-items-center">
    <div class="col-6">
      
    </div>
    <div class="col-6">
      <input class="form-control" type="text" id="myInput" onkeyup="myFunction()" placeholder="Buscar" title="Type in a name">
    </div>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Setor</th>
        <th scope="col">Ramal</th>
        <th scope="col">email</th>
        <th scope="col">Departamento</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody id="myTable">
      <% @ramals.each do |ramal| %>
        <tr>
          <td><small><%= ramal.setor %></small></td>
          <td><small><%= ramal.telefone %></small></td>
          <td><small><%= ramal.email %></small></td>
          <td><small><small><%= ramal.department %></small></small></td>
          <!--<td><%= link_to 'Mostrar', ramal, class: "btn btn-success" %></td>
          <td><%= link_to 'Editar', edit_ramal_path(ramal), class: "btn btn-warning" %></td>
          <td><%= link_to 'Apagar', ramal, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger" %></td>-->
        </tr>
      <% end %>
    </tbody>
  </table>
  <script>
      function myFunction() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
          td = tr[i].getElementsByTagName("td")[0];
          if (td) {
            txtValue = td.textContent || td.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
              tr[i].style.display = "";
            } else {
              tr[i].style.display = "none";
            }
          }       
        }
      }
</script>
  <%= link_to 'Novo Ramal', new_ramal_path, class: "btn btn-success" %>
  <br><br>
</div>

app/views/ramals/new.html.erb
<div class="container">
  
  <div class="row align-items-center mt-5 mb-5">
      <div class="col-6">
      <h3>Importar lista de ramais</h3>
        <%= form_tag import_from_excel_path, multipart: true do %>
          <%= file_field_tag :file %>
          <%= submit_tag "Importar", :class=> "btn btn-success"%>
        <% end %>
      </div>
      <div class="col-6">
        <h3>Limpar lista de ramais</h3>
        <%= link_to "Limpar lista", remove_all_ramals_path, :method => :get, class: "btn btn-danger" %>
      </div>
    </div>
  <div>
  <div class="row align-items-center">
      <div class="col-3">
      
      </div>
      <div class="col-6">
        <h1>Novo Ramal</h1>
      </div>
      <div class="col-3">
      
      </div>
  </div>
  <%= render "form", ramal: @ramal %>

  <br>

    <%= link_to "Back to ramals", ramals_path, class:"btn btn-primary mb-3" %>
  </div>
</div>

app/views/ramals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ramal %>

<div>
  <%= link_to "Edit this ramal", edit_ramal_path(@ramal), class: "btn btn-warning" %> 
  <%= link_to "Back to ramals", ramals_path, class: "btn btn-success" %>
  <br><br>

  <%= button_to "Destroy this ramal", @ramal, method: :delete, class: "btn btn-danger" %>
</div>